language: java
jdk:
  - oraclejdk11
  - openjdk11

script:
  - mvn test
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

after_success:
  - bash <(curl -s https://codecov.io/bash)